name: "Build and deploy docs"
on:
  push:
    branches:
      - main
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed for mike to push docs
    steps:
    - name: Checkout
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: 0
        lfs: false
        persist-credentials: false

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5
      with:
        python-version: '3.10'
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"

    - name: Install dependencies with uv
      run: uv sync --extra doc

    - name: strip output except plots and prints from tutorial notebooks
      run: |
        uv run python tests/strip_notebook_outputs.py tutorials/

    - name: convert notebooks to markdown
      run: |
        cd mkdocs
        uv run jupyter nbconvert --to markdown ../docs/tutorials/*.ipynb --output-dir docs/tutorials/
        uv run jupyter nbconvert --to markdown ../docs/advanced_tutorials/*.ipynb --output-dir docs/tutorials/
        uv run jupyter nbconvert --to markdown ../docs/how_to_guide/09_sampler_interface.ipynb --output-dir docs/tutorials/

    - name: Configure Git user for bot
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Build and deploy dev documentation upon push to main
      if: ${{ github.event_name == 'push' }}
      run: |
        cd mkdocs
        uv run mike deploy dev --push

    - name: Build and deploy the lastest documentation upon new release
      if: ${{ github.event_name == 'release' }}
      env:
        RELEASE_NAME: ${{ github.event.release.name }}
      run: |
        cd mkdocs
        uv run mike deploy "$RELEASE_NAME" latest -u --push
