name: "docs"
on:
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: Check Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: false

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache dependency
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip

    - name: Install sbi and dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[doc]

    - name: Build documentation
      run: |
        cd docs
        mkdocs build

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/site/
